name: Deploy App Cep no Aws
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: build project
        run: mvn clean install -DskipTests

      - name: login docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: build docker image
        run: docker build -t ricsant03/cep .

      - name: push image docker
        run: docker push ricsant03/cep

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: pull image from docker hub
        run: docker pull ricsant03/cep:latest
      - name: remove docker container
        run: docker rm -f cep-aws1
      - name: run docker container
        run: docker run -d -p 8080:8080 --name cep-aws1 ricsant03/cep





